export const widthSetter = [
  { key: "event", width: 220 },
  { key: "origin", width: 220 },
  { key: "guest_name", width: 200 },
  { key: "phone", width: 200 },
  { key: "status", width: 90 },
  { key: "state", width: 90 },
  { key: "housing", width: 220 },
  { key: "reason", width: 200 },
  { key: "tags", width: 250 },
  { key: "ts_create", width: 180 },
  { key: "arrival_date", width: 135 },
  { key: "departure_date", width: 135 },
  { key: "guestProfileStatus", width: 150 },
  { key: "caution", width: 120 },
  { key: "ciType", width: 200 },
  { key: "access_device", width: 250 },
  { key: "accountManagers", width: 200 },
  { key: "final_price", width: 120 },
];
